name=input("enter name:")
rollno=input("enter rollno:")
sub1=int(input("enter marks:"))
sub2=int(input("enter marks:"))
sub3=int(input("enter marks:"))
tm=sub1+sub2+sub3
avg=tm/3
print("----------------------------------------------------------------------")
print("                 marks report           ")
print("----------------------------------------------------------------------")
print("name",name)
print("rollno",rollno)
print("-------------------------------------------------------------")
print("sub1",sub1)
print("sub2",sub2)
print("sub3",sub3)
print("------------------------------------------------------------------")
print("tm",tm)
print("avg",avg)
print("--------------------------------------------------------------------")
